# Site Settings
name: xXxDatingxXx
title: xXxDatingxXx ❤️ Hot Online Dating For Adults
description: >-
  xXxDatingxXx ❤️ Adult Sites Collection: Dating, Sex Games, Best Porn Sites. We
  Are Adults! ❤️ Join Us Now!
tags:
  - adult
  - dating
  - adult dating
show_hero: true
email: youremail@xyz.com
disqus_username: disqus_username
paginate: 10


# Social Media Settings
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username


# Theme Settings
themeColor: '#ac0b11'
primaryDark: '#141414'
accentDark: '#ffffff'
lightGray: '#f2f2f2'
texts: '#333333'


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://xxxdatingxxx.org/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: false
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
